FROM almalinux:9
RUN dnf install nginx -y
COPY index.html /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/vidyasagaruidev/notes/main/users.txt.txt /tmp
CMD ["nginx","-g","daemon off;"]